# Generated by Django 4.0.3 on 2022-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='personalportfolio/images/')),
                ('uniform', models.URLField(blank='True')),
            ],
        ),
    ]
