# Generated by Django 4.0.3 on 2022-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uniform',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description2',
        ),
    ]
